# Generated by Django 5.0.4 on 2024-04-29 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calorie', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_burning_calorie', models.BooleanField()),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calorie_diaries.diary')),
            ],
        ),
    ]
